"use client";
import { signIn } from "next-auth/react";
import { useState, type FormEvent } from "react";
export default function Login() {
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setBusy(true);
    setError("");
    const data = new FormData(event.currentTarget);
    const result = await signIn("credentials", {
      email: data.get("email"),
      password: data.get("password"),
      redirect: false,
    });
    setBusy(false);
    if (result?.ok) window.location.assign("/");
    else setError("Unable to sign in. Check your credentials.");
  }
  return (
    <section className="card p-8 max-w-md mx-auto space-y-5">
      <h1 className="text-3xl font-bold gradient-text">
        Sign in to TradeGoons
      </h1>
      <p>Private paper-trading journal. No brokerage connection.</p>
      <form onSubmit={submit} className="space-y-4">
        <label className="block">
          Email
          <input
            name="email"
            type="email"
            autoComplete="username"
            required
            className="block w-full bg-gray-900 p-2 rounded"
          />
        </label>
        <label className="block">
          Password
          <input
            name="password"
            type="password"
            autoComplete="current-password"
            required
            className="block w-full bg-gray-900 p-2 rounded"
          />
        </label>
        <button disabled={busy} className="bg-violet-600 rounded px-4 py-2">
          {busy ? "Signing in…" : "Sign in"}
        </button>
      </form>
      {error && <p role="alert">{error}</p>}
      <p className="text-sm text-gray-400">
        For the local demo, use the synthetic accounts generated by the seed
        command. Credentials are in the local demo file.
      </p>
    </section>
  );
}
